### ISSUE TITLE
Unable to select segmented objects

### ISSUE THREAD

**Issue by K-Meech** [tischi/table-utils#2]
I am no longer able to ctrl  + click on segmented objects and have this highlight a row in the table. Conversely, I also cannot select rows from the table, and have this highlight the segmented object.

Selecting rows in the table gives a NullPointerException

**Comment by tischi** [comment]
Is the table somewhere on the server?
I need it for testing...
Maybe you can put it in the label_attributes folder on the server?

**Comment by K-Meech** [comment]
Hi!  I put it in my folder on the cba exchange

**Comment by tischi** [comment]
Ok! Can you try again?

**Comment by K-Meech** [comment]
All working again now - thanks!
